### ISSUE TITLE
Build fail: Windows host machine

### ISSUE THREAD

**Issue by Kunind** [ecobee/building-controls-simulator#54]
I used `docker-compose run --service-ports building-controls-simulator bash` to start building the image. `.env` was edited for local directory. `Gitbash` was used to execute the commands. I am running into this error at step 23 (attached: Build fail error.png and env.png)

![env](https://user-images.githubusercontent.com/30421955/94999630-a52fda80-0588-11eb-8b65-5a7908762f01.PNG)

![Build fail error](https://user-images.githubusercontent.com/30421955/94999589-44a09d80-0588-11eb-8842-88b854442a0f.PNG)

**Comment by Maharshi-Pathak** [comment]
We saved the .env to Unix format instead of the Windows file. It fails in Kunind and Emma's system at the above-mentioned step, but mine went through. I am having issues in the next step of the process, i.e. creating the network from the docker image. I get the same non-zero code error 127 when it tried to find the jupyter_lab.sh file. ( image attached)
![image](https://user-images.githubusercontent.com/64644720/95002933-6bba9780-05a7-11eb-85fc-4c75ac167b65.png)

**Comment by tomstesco** [comment]
Looks like it's failing on `sudo ./scripts/setup/install_ep.sh "${ENERGYPLUS_INSTALL_DIR}"` when the script is executed and the shell is selected from `#! /usr/bin/env`, im switching this to the basic `#!/bin/bash`. Let me know if that works for you.

Addressed in https://github.com/ecobee/building-controls-simulator/pull/63.

**Comment by Kunind** [comment]
@tomstesco I removed the docker images and ran `docker-compose...` again but I'm still getting this error. 
![image](https://user-images.githubusercontent.com/30421955/95127251-b7934b00-0725-11eb-9a48-5a3d940a72a1.png)

**Comment by tomstesco** [comment]
looks like there's something weird with the env variable expansion in docker-compose and the dockerfile. $PACKAGE_DIR might be expanding to empty string "".  

Can you run `docker inspect <container ID>` on the intermediate container and log the output here? We can check the environment variables within the container.

The container ID should still be visible when you run `docker ps -a`. Make sure to redact any sensitive environment variables, such as API keys if used.

**Comment by Kunind** [comment]
@tomstesco, here's the output (no API's used):
```
$ docker inspect 9217c4a30e67
[
    {
        "Id": "9217c4a30e67775dab6831b9900f96cbfcaeb72d1e4c5fd374705f4637bab11e",
        "Created": "2020-10-06T16:17:38.4582307Z",
        "Path": "/bin/sh",
        "Args": [
            "-c",
            "sudo chown -R \"${USER_NAME}\" \"${PACKAGE_DIR}\"     && cd \"${PACKAGE_DIR}\"     && sudo chmod +x \"./scripts/setup/install_ep.sh\"     && sudo ./scripts/setup/install_ep.sh \"${ENERGYPLUS_INSTALL_DIR}\"     && cd \"${PACKAGE_DIR}\"     && pipenv install --dev --skip-lock     && cd \"${EXT_DIR}/PyFMI\"     && . ${HOME}/.local/share/virtualenvs/$( ls \"${HOME}/.local/share/virtualenvs/\" | grep \"${PACKAGE_NAME}\" )/bin/activate     && python \"setup.py\" install --fmil-home=\"${FMIL_HOME}\""
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 1,
            "Error": "",
            "StartedAt": "2020-10-06T16:17:39.0029163Z",
            "FinishedAt": "2020-10-06T16:17:39.7992765Z"
        },
        "Image": "sha256:310bea8e61e64916f07d698898048c41e7f99b342ccc7b78bd5c15c9d8183ba5",
        "ResolvConfPath": "/var/lib/docker/containers/9217c4a30e67775dab6831b9900f96cbfcaeb72d1e4c5fd374705f4637bab11e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/9217c4a30e67775dab6831b9900f96cbfcaeb72d1e4c5fd374705f4637bab11e/hostname",
        "HostsPath": "/var/lib/docker/containers/9217c4a30e67775dab6831b9900f96cbfcaeb72d1e4c5fd374705f4637bab11e/hosts",
        "LogPath": "",
        "Name": "/goofy_hugle",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "none",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": null,
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/83e07d669d24de72aa09f7db3dd973220073d080261892d4e88ca9125340830d-init/diff:/var/lib/docker/overlay2/018576d7d117a5bd95849b0e91de75f423ce113bed91226a3a7e97f895946d58/diff:/var/lib/docker/overlay2/482e74275b30ecde981606e0e7096f585b7e733e565ea78636d7a1ef5cc7ce46/diff:/var/lib/docker/overlay2/ccc40de8e9d1e70b054ffea6a456d7f6572ebd778f32c2ea2b0ba29134092a75/diff:/var/lib/docker/overlay2/4cb8c9a4cacb8ca1629613b482102d4163d8a1096ed98d4d34f8708160f91fec/diff:/var/lib/docker/overlay2/d2a2e14c2b8419fec4aabfa1234819e9e9db57a496de53f4aba9a97ddc5b9f0a/diff:/var/lib/docker/overlay2/08d341a112f48f43f0c5f9ff884e5916fd987d133c396b0937feb100c4b4410a/diff:/var/lib/docker/overlay2/65ec761d93379813cd2c69ee3e6b5e863ecce0d03ce65c95b6dca2fa60cca07d/diff",
                "MergedDir": "/var/lib/docker/overlay2/83e07d669d24de72aa09f7db3dd973220073d080261892d4e88ca9125340830d/merged",
                "UpperDir": "/var/lib/docker/overlay2/83e07d669d24de72aa09f7db3dd973220073d080261892d4e88ca9125340830d/diff",
                "WorkDir": "/var/lib/docker/overlay2/83e07d669d24de72aa09f7db3dd973220073d080261892d4e88ca9125340830d/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "9217c4a30e67",
            "Domainname": "",
            "User": "bcs",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/home/bcs/.local/bin:/home/bcs/pyenv/shims:/home/bcs/pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "LC_ALL=C.UTF-8",
                "USER_NAME=bcs",
                "IS_DOCKER_ENV=true",
                "PACKAGE_NAME=building-controls-simulator",
                "PYENV_SHELL=bash",
                "HOME=/home/bcs",
                "LIB_DIR=/home/bcs/lib",
                "EXT_DIR=/home/bcs/lib/external",
                "ENERGYPLUS_INSTALL_DIR=/home/bcs/lib/external/EnergyPlus",
                "FMIL_HOME=/home/bcs/lib/external/FMIL/build-fmil",
                "PACKAGE_DIR=/home/bcs/lib/building-controls-simulator",
                "PYENV_ROOT=/home/bcs/pyenv",
                "DEBIAN_FRONTEND=noninteractive"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "sudo chown -R \"${USER_NAME}\" \"${PACKAGE_DIR}\"     && cd \"${PACKAGE_DIR}\"     && sudo chmod +x \"./scripts/setup/install_ep.sh\"     && sudo ./scripts/setup/install_ep.sh \"${ENERGYPLUS_INSTALL_DIR}\"     && cd \"${PACKAGE_DIR}\"     && pipenv install --dev --skip-lock     && cd \"${EXT_DIR}/PyFMI\"     && . ${HOME}/.local/share/virtualenvs/$( ls \"${HOME}/.local/share/virtualenvs/\" | grep \"${PACKAGE_NAME}\" )/bin/activate     && python \"setup.py\" install --fmil-home=\"${FMIL_HOME}\""
            ],
            "Healthcheck": {
                "Test": [
                    "NONE"
                ]
            },
            "Image": "sha256:310bea8e61e64916f07d698898048c41e7f99b342ccc7b78bd5c15c9d8183ba5",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "6cbc9164a258020c45e60c6b6b3e03ead1a3841fc65e4e9dc1a6c9e080a1c7d8",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/6cbc9164a258",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d3abcd2ecfe1f1f834e88b5ec086ea92f27513800fb62c3257d1f39e1886b91b",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]
```

**Comment by tomstesco** [comment]
the env variables are there. Can you start the container with `docker start -i <container ID>` and see if you can locate the missing file?

**Comment by Kunind** [comment]
I can locate the file, seems like a syntax error.
![image](https://user-images.githubusercontent.com/30421955/95461317-16361000-0944-11eb-883c-369b8311bb0b.png)

**Comment by thisIsMikeKane** [comment]
I've looked into this a bit further by modifying to `Dockerfile` to help with debugging by echoing directories. 

``` bash
RUN sudo chown -R "${USER_NAME}" "${PACKAGE_DIR}" \
    && cd "${PACKAGE_DIR}" \
    && sudo pwd \
	&& sudo ls -la "./scripts/setup" \
    && sudo chmod +x "./scripts/setup/install_ep.sh" \
    && sudo ./scripts/setup/install_ep.sh "${ENERGYPLUS_INSTALL_DIR}" \
    && cd "${PACKAGE_DIR}" \
    && pipenv install --dev --skip-lock \
    && cd "${EXT_DIR}/PyFMI" \
    && . ${HOME}/.local/share/virtualenvs/$( ls "${HOME}/.local/share/virtualenvs/" | grep "${PACKAGE_NAME}" )/bin/activate \
    && python "setup.py" install --fmil-home="${FMIL_HOME}"
```

This returned the following that shows that `install_ep.sh` appears to be where it should be, but the `chmod` command still cannot find it. 

```bash
Step 23/25 : RUN sudo chown -R "${USER_NAME}" "${PACKAGE_DIR}"     && cd "${PACKAGE_DIR}"     && sudo pwd
        && sudo ls -la "./scripts/setup"     && sudo chmod +x "./scripts/setup/install_ep.sh"     && sudo ./scripts/setup/install_ep.sh "${ENERGYPLUS_INSTALL_DIR}"     && cd "${PACKAGE_DIR}"     && pipenv install --dev --skip-lock     && cd "${EXT_DIR}/PyFMI"     && . ${HOME}/.local/share/virtualenvs/$( ls "${HOME}/.local/share/virtualenvs/" | grep "${PACKAGE_NAME}" )/bin/activate     && python "setup.py" install --fmil-home="${FMIL_HOME}"
 ---> Running in c3d033b3254a
/home/bcs/lib/building-controls-simulator
total 44
drwxr-xr-x 1 bcs root 4096 Oct  7 14:18 .
drwxr-xr-x 1 bcs root 4096 Oct  7 14:18 ..
-rwxr-xr-x 1 bcs root 5578 Sep 30 18:01 .bashrc
-rwxr-xr-x 1 bcs root 1408 Oct  7 14:18 download_IECC_idfs.sh
-rwxr-xr-x 1 bcs root 2643 Oct  7 14:18 install_ep.sh
-rwxr-xr-x 1 bcs root 1316 Oct  7 14:18 jupyter_lab.sh
-rwxr-xr-x 1 bcs root  757 Jun  4 17:23 jupyter_lab_bkgrnd.sh
-rwxr-xr-x 1 bcs root  221 Oct  7 14:18 test_env_setup.sh
sudo: unable to execute ./scripts/setup/install_ep.sh: No such file or directory
ERROR: Service 'building-controls-simulator' failed to build : The command '/bin/sh -c sudo chown -R "${USER_NAME}" "${PACKAGE_DIR}"     && cd "${PACKAGE_DIR}"     && sudo pwd     && sudo ls -la "./scripts/setup"     && sudo chmod +x "./scripts/setup/install_ep.sh"     && sudo ./scripts/setup/install_ep.sh "${ENERGYPLUS_INSTALL_DIR}"     && cd "${PACKAGE_DIR}"     && pipenv install --dev --skip-lock     && cd "${EXT_DIR}/PyFMI"     && . ${HOME}/.local/share/virtualenvs/$( ls "${HOME}/.local/share/virtualenvs/" | grep "${PACKAGE_NAME}" )/bin/activate     && python "setup.py" install --fmil-home="${FMIL_HOME}"' returned a non-zero code: 1
```

Hope this helps with the debugging

**Comment by tomstesco** [comment]
really strange - maybe adding the full path will help. Editting the Dockerfile with the build step
```bash
RUN sudo chown -R "${USER_NAME}" "${PACKAGE_DIR}" \
    && cd "${PACKAGE_DIR}" \
    && sudo chmod +x "${PACKAGE_DIR}/scripts/setup/install_ep.sh" \
    && sudo "${PACKAGE_DIR}/scripts/setup/install_ep.sh" "${ENERGYPLUS_INSTALL_DIR}" \
    && cd "${PACKAGE_DIR}" \
    && pipenv install --dev --skip-lock \
    && cd "${EXT_DIR}/PyFMI" \
    && . ${HOME}/.local/share/virtualenvs/$( ls "${HOME}/.local/share/virtualenvs/" | grep "${PACKAGE_NAME}" )/bin/activate \
    && python "setup.py" install --fmil-home="${FMIL_HOME}"
```

**Comment by Kunind** [comment]
Still getting the same error.
![image](https://user-images.githubusercontent.com/30421955/95505463-5f09bb00-097c-11eb-91e7-a0706eaa4ac9.png)

**Comment by thisIsMikeKane** [comment]
@kunind, Maybe this has to do with CR LF end of line on Windows vs Linux?

**Comment by Kunind** [comment]
@thisIsMikeKane Using notepad++, I changed the encoding to Unix (LF). Still getting the same error.

**Comment by tomstesco** [comment]
Good suggestion. Try removing the lines for that script outright and see if you get another error, there could be something else underlying it. Also, you can run the E+ install script after the container builds - just less convenient.

```
RUN sudo chown -R "${USER_NAME}" "${PACKAGE_DIR}" \
    && cd "${PACKAGE_DIR}" \
    && pipenv install --dev --skip-lock \
    && cd "${EXT_DIR}/PyFMI" \
    && . ${HOME}/.local/share/virtualenvs/$( ls "${HOME}/.local/share/virtualenvs/" | grep "${PACKAGE_NAME}" )/bin/activate \
    && python "setup.py" install --fmil-home="${FMIL_HOME}"
```

**Comment by Kunind** [comment]
@thisIsMikeKane @tomstesco I was changing the encoding of the `.env` file, but that was not the issue. For some reason, `install_ep.sh` file in `building-controls-simulator > scripts > setup` was encoded as Windows CR LF. As a result, the Linux system could not identify the file. I changed the encoding, and the error seems to be resolved. I'm not sure how the encoding changed automatically, probably a git sync issue.
